### ISSUE TITLE
Premium Motors

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#180]
When optimizing, 

if hp > 500 hp then use 500 hp

if poles > 6, use poles = 6

**Comment by pshires** [comment]
potentially we could use energy efficient energy efficiency class in optimal if the user is dealing with large horsepower motors

**Comment by koay9f** [comment]
I think something is wrong... may need to wait for Asha.

for 60 Hz, 200 hp, 1780 RPM:
FLA
Standard: 228.57
EE: 225.8
PE: 227.16
This should not be a parabola.

Efficiency is good
Standard: 94
EE: 95.7
PE: 96.3

**Comment by pshires** [comment]
I showed Asha this and she seemed to think it was working. We did not extensively test it, however.

**Comment by koay9f** [comment]
yeah, I know.  but it is still not right. so we need to sit down and talk about it

**Comment by koay9f** [comment]
Daryl wasn't sure which way this would go, so hopefully it will resolve itself with #188
