### ISSUE TITLE
75% rule for circular planes rework

### ISSUE THREAD

**Issue by pshires** [ORNL-AMO/AMO-Tools-Suite#200]
This variable calculation will need to be reworked for circular planes, this shouldn't be a large task, but it might as well wait until we talk with flow care and ask some questions about circular planes.  See Planar.cpp line 62

**Comment by gaccawi** [comment]
Send an email.

**Comment by pshires** [comment]
The email was sent and responded to, the currently existing code will work just fine for both rectangular and circular planes
