### ISSUE TITLE
Update to SSMT T-S graph

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#237]
Need code to make user input line for steam graphs

**Comment by pshires** [comment]
https://github.com/ORNL-AMO/AMO-Tools-Suite/blob/generate-steam-data/tests/js/ssmtTest.js#L9

here is what we have. This *should* be completed, (hopefully), but it has no real unit test yet. I linked an example of usage however, so it should be testable with a local build

**Comment by pshires** [comment]
@DmitryHoward @koay9f

**Comment by gaccawi** [comment]
Add a unit test
