### ISSUE TITLE
Pump Table Creation

### ISSUE THREAD

**Issue by FontenotZach** [ORNL-AMO/AMO-Tools-Suite#258]
Create a pump table in the indexed db for use in desktop.

**Comment by rmroot** [comment]
https://github.com/ORNL-AMO/AMO-Tools-Suite/pull/262

**Comment by koay9f** [comment]
From Preston's PR
Added:
PumpData constructor
PD table creation, deletion and update

Needed:
Unit test
Confirmation pump table is being created correctly
