### ISSUE TITLE
Fan Operating points planar data table zeros

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#259]
There are zeros for plane 3's velocity and total pressures

is it possible that for the `flowTraverse` class? (and the additional ones) that the `flowTraverse.pv3` is not actually getting tied to `flowTraverse.gasVelocityPressure`
so for the table it has nothing for `gasVelocityPressure`
and the calculation
`planeData.flowTraverse.gasTotalPressure =
               planeData.flowTraverse.staticPressure + planeData.flowTraverse.gasVelocityPressure;`
is returning NaN (or zero) b/c `planeData.flowTraverse.gasVelocityPressure` is NaN (or zero)

**Comment by koay9f** [comment]
[operating points example.pptx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e4d74908d93000118c87fb/125516c66e82c728ace21e0d46e7849f318397a081eeff53ab54fe803a06226b2809b32775c7af6aaf50740b0a0c0abe4b4a5a4da8acdb7aa4e23577db0a59bfd16d5a73903c14ffea840da313f871d51bdaebe5c01982fa3737e682854e3b1d071d8dfa5e32a19f4ec04abb.pptx)

**Comment by koay9f** [comment]
Hopefully this is useful.  it is the only pptx I have that seems relevant

[https://app.zenhub.com/files/75637129/8bda14cc-58bc-447b-8d21-50e54cf01845/download](https://app.zenhub.com/files/75637129/8bda14cc-58bc-447b-8d21-50e54cf01845/download)

**Comment by rmroot** [comment]
The values were not being calculated at all. Just initialized to zero
