### ISSUE TITLE
Steam Turbine - Units

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Suite#261]

**Comment by rmroot** [comment]
![steam-turbine-ssmt.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46fb809f228fcebd9afbbd4aaa58bd873a4b33316546b3397f8fe62bab0021435a561af913095d10f5fed87df4e43c708f5b5decd43e0d72d42103eee9dc4be05ce36ade0d97bcae8b4bcae93826e5828847391a021e80fc4f78.PNG)
![steam-turbine-desktop.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46fb809f228fcebd9afbbd4aaa58bd902c552c672614e1673295f127b54778154d555ca9480c0a16adfbdd22a1e76a22d85c0be8d63b5e71956f17bea4905dee5fee7fd616cfe3fe9846d2e9352fe68e8c4d37190d1f8cfb5e31a18b06.PNG)

**Comment by rmroot** [comment]
The suite seems to be returning Mass flow in `tonne/hr` instead of `kg/hr`. It also just returns a single massFlow result, not one for inlet and one for outlet. 

Is "Energy Out" and "Power Out" both alwasy kW? if so is there a reason my numbers are soo off?

branch with this is called `issue-2140`

**Comment by rmroot** [comment]
All other steam calculators return mass flow in `kg/hr`

**Comment by koay9f** [comment]
Your numbers are off b/c on the SSMT you have your pressure set to barg, which means bar gauge.  Our tool uses absolute pressures (there is an issue about if if you are interested), but in the mean time, you need to be sure to set your SSMT pressures to an absolute pressure.

Also, yes, some of the values the C++ uses are in a different unit than you were expecting..


C++ input:
Mass flow (if dropdown is set to mass flow): kg/hr
Power out (if the dropdown is set to power): MJ/hr

C++ output:
Mass flow: tonne/hr
Power out; Energy flow: MJ/hr

Energy flow and power use should be set by the users (independently) but use the same list of possible units.  Defaults are MJ/hr (MMBtu/hr – imperial) and kW respectively

![image](https://user-images.githubusercontent.com/25389736/43428417-21b63ffc-942c-11e8-9354-17f23f7a05bc.png)

let me know if this doesn't make sense
