### ISSUE TITLE
Review Doxygen - Calculators

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#283]

**Comment by Aeledbetter** [comment]
`PercentAvgkWhElectricCostAvoided,  StandbyRate,  annualElectricityConsumption, annualThermalDemand,  boilerThermalFuelCosts,  avgElectricityCosts, calculationOption, boilerThermalFuelCostsCHPcase, CHPfuelCosts, percentAvgkWhElectricCostAvoidedOrStandbyRate,  displacedThermalEfficiency, chpAvailability, thermalUtilization`
This is for CHP

And also `inletPressure, outletPressure,  flowRate` under compressed air
