### ISSUE TITLE
Known SSMT Bug

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#294]
Keep in mind when coding

From Expert:

If I recall correctly, the 2 header model has a bug specifically with properly triggering the desuperheating. This looks like another example of that bug. The best workaround (other than fixing the bug) would be to adjust the model to include a 3rd header that doesn't impact the overall model. For example a 3rd header with a pressure of 15.999 could be added with next to no impact.  By adding the 3rd header, the desuperheating should work correctly.

**Comment by koay9f** [comment]
It looks like the MEASUR desktop model does not have this bug
SSMT:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/5f5355df-3da7-4782-a876-df6c40714089)
MEASUR:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f94ebe41-e5c4-46dd-a856-07c5639bccb8)

Can be closed when AT 5 passes (double check that the results for AT 5 have values in PRV feedwater pipe and matches more to MEASUR than SSMT)

**Comment by jeffjensen** [comment]
@koay9f AT 5 passes, does it fulfill all the concerns with this issue?
