### ISSUE TITLE
Flash Tank Bug

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#304]
Need to add a switch at line 25.
Current line 25 - 26
`double const liquidMassFlow = inletWaterMassFlow * (inletWaterProperties.specificEnthalpy - saturatedProperties.gasSpecificEnthalpy)
						  / (saturatedProperties.liquidSpecificEnthalpy - saturatedProperties.gasSpecificEnthalpy);`

Replace those lines with a switch:

case: inletWaterProperties.specificEnthalpy > saturatedProperties.gasSpecificEnthalpy
double const liquidMassFlow = 0

case: inletWaterProperties.specificEnthalpy < saturatedProperties.liquidSpecificEnthalpy
double const liquidMassFlow = inletWaterMassFlow 

all other cases
double const liquidMassFlow = inletWaterMassFlow * (inletWaterProperties.specificEnthalpy - saturatedProperties.gasSpecificEnthalpy)
						  / (saturatedProperties.liquidSpecificEnthalpy - saturatedProperties.gasSpecificEnthalpy);

**Comment by rmroot** [comment]
All outlet liquid properties need to be the same as inlet if "nothing is flashed"

**Comment by koay9f** [comment]
Okay, I'm an idiot apparently.  I appologize, I don't have any clue how to write the new parts in C++

In addition to the setting the mass flows...

Case: inletWaterProperties.specificEnthalpy > saturatedProperties.gasSpecificEnthalpy
outlet properties = steam properties (Pressure = Pressure, Quality = 1)


case: inletWaterProperties.specificEnthalpy < saturatedProperties.liquidSpecificEnthalpy
outlet properties = steam properties (Pressure = Pressure, Quality = 0)



all other cases

there should be something already there

I think the outlet properties might be already calculated in those `sp` lines, but I'll admit, I have no idea what is going on.


Here is the original php code if that helps:
/library/Steam/Equipment/FlashTank.php

**Comment by rmroot** [comment]
I believe we just need to add the case checks to the C++. There currently is no check of the inlet quality before calculations.
