### ISSUE TITLE
SSMT - Region Select Error

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Suite#329]
Is there an alternative to a runtime error for this regionSelect function. 

A runtime error stops all calculations and locks up the app.

**Comment by rmroot** [comment]
![region-select-error.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/578d0f5c93a8430e00038879/125516c66e82c728ace21e0d46fa919d2a8d8de49cecb346a749bd913b5428616b48e13b628ae92dbc56395b4d5a47f8140a0e46a8f08e7af0e46e708a590cbbd0680c26c02f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e28a87463f1c061b8bf65527ed.PNG)

**Comment by rmroot** [comment]
I tested by returning 4 instead of throwing error and calcs didnt crash. Couldn't verify results were accurate

**Comment by pshires** [comment]
we don't have to throw runtime errors, but we need to halt the calculation from my understanding. If this region selection process fails, then the entire calculation is basically worthless at that point (i think). @koay9f can you confirm that we do need to absolutely halt further calculation?

**Comment by koay9f** [comment]
I think so.  If it can't select a region, then whatever it spits out isn't valid.
