### ISSUE TITLE
TH - Compressed Air Leak Survey

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#350]
Issue overview
--------------

Where is math?

**Comment by koay9f** [comment]
Should just be able to use the CA reduction calculations for most.  Will be adding one more calc method to that for Orifice Method.

**Comment by causeyc** [comment]
This is a new calculator

**Comment by causeyc** [comment]
[https://app.zenhub.com/files/75637129/12dcbd06-7678-4b98-8b1f-4ab704cc901c/download](https://app.zenhub.com/files/75637129/12dcbd06-7678-4b98-8b1f-4ab704cc901c/download)
