### ISSUE TITLE
WebAssembly Bindings - ssmt.h

### ISSUE THREAD

**Issue by DmitryHoward** [ORNL-AMO/AMO-Tools-Suite#454]
Issue overview
--------------
Convert ssmt.h NAN bindings to WebAssembly module. Include exposed endpoints in the Makefile.

**Comment by rmroot** [comment]
Standalone steam calculators have been implemented. Steam modeler bindings have not been written.

**Comment by omerbaa** [comment]
steam modeler wasm implemented / created tests
