### ISSUE TITLE
Database materials cleanup

### ISSUE THREAD

**Issue by pshires** [ORNL-AMO/AMO-Tools-Suite#46]
There are duplicate string names in the database for different materials. Each material needs to be uniquely named.

**Comment by pshires** [comment]
Kiran suggests using this for the duplicate strings
"
Die casting metal (Aluminium alloy)  - 0.236, 163 ……
Die casting metal (Lead alloy)        - 0.038…..
Die casting metal (Tin alloy)   - 0.07…..
Die casting metal (Zinc alloy)    - 0.1029 ……
 
Feel free to use the symbols (Al, Pb, Sn, Zn) in place of the names
"

**Comment by gaccawi** [comment]
Done and resolved.
