### ISSUE TITLE
Density Calculation Not Matching FSAT

### ISSUE THREAD

**Issue by AlexBotts** [ORNL-AMO/AMO-Tools-Suite#482]
Issue overview
--------------
FSAT is giving different final answers. The density is not matching as it should.

**Comment by koay9f** [comment]
May be solved by #481

**Comment by koay9f** [comment]
will not be solved by #481
here is what to do.  [https://app.zenhub.com/files/75637129/e3f72c4e-79c3-4a3d-9c3b-f7a3634469b3/download](https://app.zenhub.com/files/75637129/e3f72c4e-79c3-4a3d-9c3b-f7a3634469b3/download)
