### ISSUE TITLE
Make something to calculate values for / based on Motor Database

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#495]
need "standard" motor full load efficiency for the following combinations
MotorEfficiency::calculate(double loadFactor, double specifiedEfficiency)
loadFactor = 1 (might be 100 not sure)
efficiencyClass == Motor::EfficiencyClass::STANDARD
hp = {1, 1,5, 2, 3, 5, 7.5}, sequence(10,30,5), {40, 50, 60}, sequence (75, 150, 25), sequence(150, 500, 50)
rpm = 900, 1200, 1800, 3600 EDIT: SEE BELOW
linefrequency= 50,60

**Comment by AlexBotts** [comment]
For rpm there will be 8 levels (4 for each Hz level)

rpm = 900,1000,1200,1500,1800,3000,3600
