### ISSUE TITLE
ESC 31 Use of Economizer

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#538]
[https://app.zenhub.com/files/75637129/96e8c478-9301-48ad-9ce4-751d3068405c/download](https://app.zenhub.com/files/75637129/96e8c478-9301-48ad-9ce4-751d3068405c/download)Issue overview

---

I have an excel if you need it

--------------

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/75637129/96c9bf06-328e-4b1d-85c2-b96de2273b36/download](https://app.zenhub.com/files/75637129/96c9bf06-328e-4b1d-85c2-b96de2273b36/download)

**Comment by omerbaa** [comment]
implemented in #609

**Comment by omerbaa** [comment]
fix #618
