### ISSUE TITLE
Exhaust Gas - Other Losses for Electric Arc furnace (EAF)

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Suite#54]
Args: 
off_gas_temp (deg F)
CO (%)
H2 (%)
O2 (%)
CO2 (%)
combustible_gases (%)
vfr (volume flow rate, cfm) 
dust_loading (s/scf)
other_losses (n number, btu/cycle)

**Comment by gaccawi** [comment]
Step 1: Find heating value of gases
co_heating_value = CO * 321;
h2_heating_value = H2 * 325;
combustibles = combustible_gases * 1020;
chemical_heat = co_heating_value + h2_heating_value + combustibles;

Step 2: Total volume flow rate
total_vfr = vfr * 520/(460 + off_gas_temp);

Step 3: Sensible heat
sensible_heat = 0.0225 * (CO2 - 60);

Step 4: Heat in dust
heat_in_dust = dust_loading * 0.25 * (CO2 - 60);

Step 5: Total heat in flue gases
total_heat_flue = chemical_heat + sensible_heat + heat_in_dust;

Step 6: Total heat in exhaust gases (btu/cycle)
total_heat_exhaust = H2 * total_vfr * total_heat_flue * 60;

**Comment by gaccawi** [comment]
Need to find how other losses come into play. Looks like maybe a sum of the other losses.

**Comment by gaccawi** [comment]
See https://github.com/ORNL-AMO/AMO-Tools-Desktop/issues/184

https://cloud.githubusercontent.com/assets/8973004/25197136/f81f6a0a-2510-11e7-8198-21de526460c5.png

**Comment by akferree** [comment]
For sensible heat and heat in dust, the Excel sheet shows the formulas below:

sensibleHeat = 0.0225*(offGasTemp - 60)

heatInDust = dustLoading*0.25*(offGasTemp - 60)

**Comment by akferree** [comment]
<img width="650" alt="capture" src="https://user-images.githubusercontent.com/21345679/27149948-6189abbc-5113-11e7-8f36-209b01183151.PNG">
