### ISSUE TITLE
Compressed Air Pressure Reduction Math change

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#546]

**Comment by koay9f** [comment]
=compressorPower * (((pressure + atmosphericPressure) / atmosphericPressure) ^ (0.395/1.395)-1)/ (((pressureRated + 14.7) / 14.7) ^ (0.395/1.395)-1)


NEW VARIABLE - "pressureRated"
Imperial Unit: psig
Metric Unit: same as "pressure"
Field Name: Rated Pressure
Help text (I know, this is a desktop thing): Pressure at rated flow per CAGI data sheet or manufacturer specified design inlet pressure

NEW VARIABLE - "atmosphericPressure"
Field Name: Atmospheric Pressure
Imperial Unit: psia
Metric Unit: same as "pressure" but "a"
Help text: same as other atmospheric pressures

**Comment by AlexBotts** [comment]
I can confirm the math @koay9f wrote out is correct.

**Comment by koay9f** [comment]
@AlexBotts lies!

Correction:
mod.power =compressorPower * (((pressure + atmosphericPressure) / atmosphericPressure) ^ ((0.395/1.395)-1)/ (((pressureRated + 14.7) / 14.7) ^ ((0.395/1.395)-1)
baseline.annualPower = compressorPower x opHours
mod.annualPower = mod.power x opHours

new text
compressorPower = 200 kW
baseline.pressure = 100 psig
mod.pressure = 90 psig
atmosphericPressure = 14.7 psia (default to this btw)
pressureRate = 100 psig
operatingHours = 8760

mod.power=200 x (((90 + 14.7 ) / 14.7 ) ^ (0.395/1.395)-1)/ (((100 + 14.7) / 14.7) ^ (0.395/1.395)-1)
mod.power=188.437752344986
baseline.annualPower = 200 x 8760 = 1,752,000
mod.annualPower = 188.437752344986 x 8760 = 1,650,714.7
savings.annualPower = 101,285 kWh

**Comment by koay9f** [comment]
just for records.  
mod.power =compressorPower * ((((pressure + atmosphericPressure) / atmosphericPressure) ^ (0.395/1.395))-1)/ ((((pressureRated + 14.7) / 14.7) ^ (0.395/1.395))-1)
or
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/31af62e7-87f1-4679-b758-3bfab0b4d814)
