### ISSUE TITLE
Compressors - Algorithm

### ISSUE THREAD

**Issue by omerbaa** [ORNL-AMO/AMO-Tools-Suite#551]
Issue overview
--------------

**Comment by koay9f** [comment]
As of 02-12-21

Algorithms Implemented
- [x] Centrifugal Compressors
- [x] Non-centrifugal compressors
- [x] Single compressor SYSTEMS
- [ ] Multiple compressor SYSTEMS
- [ ] Energy Efficiency Measures (Explore Ops)

**Comment by omerbaa** [comment]
implemented wasm / created tests

**Comment by omerbaa** [comment]
added PressureReductionSaving & kWAdjusted, implementation and tests

**Comment by omerbaa** [comment]
#513
