### ISSUE TITLE
Furnace types

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Suite#56]
Get list of furnace types for electro technologies and fuel fired.

**Comment by akferree** [comment]
**Fuel Fired**
Electric Arc Furnace
Ladle heater 1
Ladle heater 2
Reheat furnace
Tundish heater 1
Tundish heater 2

**Electrotechnology**
Electrical Infrared
Induction Heating and Melting
Electrical Resistance
Vacuum Furnace
Electric Arc Furnace (EAF)

**Comment by rmroot** [comment]
fuelFiredOptions: Array<string> = [
    'Electric Arc Furnace',
    'Ladle Heater 1',
    'Ladle Heater 2',
    'Reheat Furnace',
    'Tundish Heater 1',
    'Tundish Heater 2'
  ]

  electrotechOptions: Array<string> = [
    'Electrical Infrared',
    'Induction Heating and Melting',
    'Electrical Resistance',
    'Vacuum Furnace',
    'Electric Arc Furnace (EAF)'
  ]

**Comment by rmroot** [comment]
Fuel Fired:
Ladle
Reheat furnace
Tundish
Generic

Electrotechnology:
Electrical Infrared
Induction Heating and Melting
Electrical Resistance
Vacuum Furnace
Electric Arc Furnace (EAF)
Generic
 
From 6/15/2017 Meeting

@gaccawi is this correct?
