### ISSUE TITLE
Remove "Round" function calls in compressed air calculations

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Suite#601]
Issue overview
--------------

The "Round" function call in the Compressors.cpp is causing some errors in accuracy. It should be removed.

![image (6).png](https://images.zenhubusercontent.com/5c9d19352250f9495b573154/95cba1bc-412f-47e9-995d-81fe25e15baf)

![image (5).png](https://images.zenhubusercontent.com/5c9d19352250f9495b573154/4c0d023e-3877-4f71-a168-8f108c077f7e)f44)

The second image has the Round function applied, the stepping is an unwanted result

**Comment by omerbaa** [comment]
changes applied
