### ISSUE TITLE
Heat Cascade Error

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#602]
Issue overview
--------------
Fix error from the Algo doc...

currently: line 21
`    const double energySavings = eqEnergySupply * effOpHours;`

Should be: line 21
`    const double energySavings = std::min(eqEnergySupply, secFiringRate) * effOpHours;`

Looks like secFiringRate may need bindings
Also pls make a binding for "hourlySavings" which = std::min(eqEnergySupply, secFiringRate)

If you want to make that tidier (add a line for hourlySavings and use that in energySavings), that is fine

**Comment by omerbaa** [comment]
changes applied
