### ISSUE TITLE
Compressor Calc Unit Testing

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Suite#617]
Issue overview
--------------
Create unit tests for each compressor and control type.

What I need is a list of compressor ID's from the generic data base in MEASUR and the expected % Power and % Capacity that you get from AirMaster.

Values can be picked at random, for types with unloading it would probably be good to have a value from before and after the unload point. 

Any other weird edge case compressors you can think of would also be good.

**Comment by AlexBotts** [comment]
[https://app.zenhub.com/files/75637129/c3b87476-b558-4606-a684-7def2872cd9b/download](https://app.zenhub.com/files/75637129/c3b87476-b558-4606-a684-7def2872cd9b/download)
