### ISSUE TITLE
Fixes to HeatWaterUsingFlue

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#618]
Issue overview
--------------
C++ not matching algorithm 
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f455d976-b439-494e-a371-457c94a7aba3)

1 - add switch to line 25
enthalpySteam = 
if condSteam == Saturated --> 
`SteamProperties(prSteam, SteamProperties::ThermodynamicQuantity::QUALITY, 1).calculate().specificEnthalpy`
else --> 
`SteamProperties(prSteam, SteamProperties::ThermodynamicQuantity::TEMPERATURE, tempSteam).calculate().specificEnthalpy`

2. remove line 24 and tempSteamSat from return (not needed)

**Comment by omerbaa** [comment]
applied fix, PR 620

**Comment by koay9f** [comment]
Can't test b/c desktop is buggy.  code looks good, but need to confirm it all works
