### ISSUE TITLE
Cascade Heat

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#622]
Issue overview
--------------

Need to update how heat cascade works

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/101b3995-0248-4a03-b943-8b80cdaea117)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/78707bc8-d81f-4424-9fe0-a3628bb793ad)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c6a36213-092a-4ca6-bb6f-641d0e50cb42)

I'll send the excel via teams.

**Comment by omerbaa** [comment]
input temperatures should  be in K not F, looking for another issue, will update once looked further
