### ISSUE TITLE
Available Heat Algorithm

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#623]
The calculations for calculating sensible heat of the fuel needs to be added to `GasCompositions::ProcessHeatPropertiesResults GasCompositions::getProcessHeatProperties`

Don't need to use the separate method, but the math should be added from lines 154 - 161.
replace `fuelTemp` with `ambientAirTempF`, do what you need to do to make it match the "style" of the rest of getProcessHeatProperties

```
double GasCompositions::calculateSensibleHeat(const double fuelTemp) {
    double specificHeatFuel = 0;
    for ( auto const & comp : gasses ) {
        specificHeatFuel += comp.second->compByWeight * (comp.second->specificHeat(520) / comp.second->molecularWeight);
    }

    return 1 * specificHeatFuel * (fuelTemp - 32);
}
```

Whatever variable you use for sensible heat needs to be added to Line 131

```
    const double availableHeat = (100 * (WhateverSensibleHeat + heatValueFuel + preHeatedAirEff + preHeatedAirMoistureEff) - (H2OHeatContent + CO2HeatContent + N2HeatContent + O2HeatContent)) / (100 * heatValueFuel);
```

A few comments to make the code more understandable:
I know I missed some that should be called out, so if there is anything you can think of to help make it more intuitive, please add.
before ...
line 47:  temperature conversions
line 54:  calculate average Cp across temperature range of combustion air to flue gas
line 84: something, not 100% sure what is right here, it is kind of used for several things
line 111: calculate heat in combustion air moisture
before whatever you add for sensible heat: calculate sensible heat
before density: calculate final values

**Comment by omerbaa** [comment]
PHASTE calculator algo and excel results dont seem to match.
If PHASTE is used for comparison with new process calc's, needs more explanation and understanding  of differences / updates between algo and excel, to know what is actually missing between two methods for calculating available heat.
