### ISSUE TITLE
Available Heat F vs. K

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#624]
Issue overview
--------------

Generally temperatures coming into the suite from process heating are in F not K.
Right now, to use the new algorithm we would have to have the desktop convert them to K and then the suite would convert back to F and they are not using the same "constants" for the conversions.
Would be best if the suite just assumed that it was in F.

HOWEVER, I know this will mess with some of the ESC's. It would be better if the files calling `GasCompositions::ProcessHeatPropertiesResults GasCompositions::getProcessHeatProperties` that have a temperature in K because it came from a steam calculator do a conversion before putting them in `getProcessHeatProperties` rather than the conversions being always in `getProcessHeatProperties`.

**Comment by omerbaa** [comment]
Duplicate already hadled in #622
