### ISSUE TITLE
More Available heat issues

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#627]
Issue overview
--------------

GasCompositions::ProcessHeatPropertiesResults GasCompositions::getProcessHeatProperties(const double flueGasTempF, const double flueGasO2, const double combAirTemperatureF, const double fuelTempF, const double ambientAirTempF, const double combAirMoisturePerc)

^ should take in excessAir instead of flueGasO2
1 - it is possible that the user actually knows their excessAir
2 - it is using an outdated method to calculate excessAir.  GasCompositions::calculateExcessAir is more accurate than getExcessAir

will there need to be a change to GasCompositions::calculateExcessAir? will it work with the changes to the rest of the gas fuel method?

**Comment by koay9f** [comment]
Current Flue gas calculations: 
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/743cd0df-ab94-4967-baac-b38154c1ae89)
Old ("correct") calculations:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/81cbce29-8035-4469-9fff-678253766b12)
Current AH calculation in condensing economizer
(also essentially correct)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/838cecf1-9869-4158-9d66-edc4ab7ad09a)

**Comment by koay9f** [comment]
More notes:
Bindings on suite side are about excessAir:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/1496d8a5-5da4-4da6-b753-c383f1bdb32e)

**Comment by omerbaa** [comment]
no need to compute excessAir, if excessAir method flueGasO2 is computed and send in the results (as fraction), use that value for flueGasO2%
send both excessAir% or flueGasO2%, depending on method set one of the parameters to zero
if calling from wasm send fraction and not % value
if calling from node bindings send % and not fraction

**Comment by omerbaa** [comment]
calculateExcessAir is just adjusting to remove delta error from calculations no magic or science behind, just mathematical adjustment, I don't believe has any thing to do with any accuracy, actually the getExcessAir is the correct method.
