### ISSUE TITLE
Publish Suite Releases and Assets

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Suite#683]
We have a backlog of suite drafts and assets that need to be published.

**Comment by nbintertech** [comment]
V1.0.3, V0.9.1 and releases preceeding V0.9.1 are corrected/accurate. To fix other releases or drafts retroactively, we would need to go back to try and find the commits between each release, then manually construct a release branch to base the published release tag off of, otherwise it will grab the targetted branch's current commit

**Comment by rmroot** [comment]
Stale. Not going to update old releases at this point. Closing
