### ISSUE TITLE
PH Excess Air iteration starting value

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#689]
Issue overview
--------------

Revert back to original
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL05iQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a6bca8e7a2996442af46d644ad60fa93daf0d43/image.png)

replacing the numbers with stoichAir/32 only works for natural gas, methane & maybe ethane.
but apparently the relationship with numbers works as a good enough starting point for most hydrocarbons.

**Comment by nbintertech** [comment]
Tested flue gas calc with below 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd253QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7aa69e28f2e0862e33a91e7a810ff21207d51f08/image.png)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2J3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f268369c9c92709689b4b9fbe784bda2b415f4c/image.png)
