### ISSUE TITLE
Update Compilation process, packages, README

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/AMO-Tools-Suite#704]
The team needs a more complete, working resource instructing us how to perform suite builds and compilation, including below: 

**1. Development Environment** - We need to assess and outline the bare minimum environment needed to develop the project on Win, Mac, Linux. Are there any packages no longer needed? What is the easiest way for Win users specifically to use make/compile cpp, etc. Divide up process --> WASM way vs NAN way if any differences

**2. Catch and Sqllite packages** - Need to check these and other libraries are up to date 

**3.  Running CPP unit tests** - Mark/Nick can no longer run them, possibly Gina as well. We need better documentation for the A) commands and B) development environment dependencies needed to run these. There will be a separate issue for fixing individual tests

Note: We'll only need to develop using the WASM bindings from here on out, but any users of the legacy repo will need a working README to use that with legacy NAN bindings

**Stretch goal:**
- If the app could be containerized, that would be best. I was able to build from the current image about 75% of the way until it failed. Not sure if worth fixing the existing dockerfile though - possibly best to start new.

**Comment by omerbaa** [comment]
Cleanup / updates / README updated

Moving forward there wont be any necessity to update CMakeFIle

**Comment by rmroot** [comment]
docker implemented and readme updated.
