### ISSUE TITLE
System Capacity: Resolve rounding issue

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Suite#715]
Issue overview
--------------
see #6802

Add more decimal precision.

From original issue:
From @AlexBotts 

Entered field value 8500 becomes 8501. What calculations are happening here?
<img width="1061" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNC84QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e87594988bbf7708ac49d6958253e7c6d7df039/image.png" alt="image.png" />

8500 gal is given to the suite as input. When it's passed back as output the value appears to be in ft3 (1136.36363636 ft3). MEASUR then converts this back to gal using our global conversion resulting in 8500.58 rounded to 8501 gal.

CompressedAir.cpp line 111
<img width="777" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUl1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48b71d0c8f32f79d0df2abe93457c32739052605/Untitled%20%288%29.png" alt="Untitled (8).png" />

**Comment by koay9f** [comment]
let's see what happens if you use whatever the conversion is between ft3 and gal in the unit converter in the desktop instead of `7.48`

**Comment by rmroot** [comment]
updated to: 7.480515625

<img width="1104" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG1EQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25399791ad22442eef0ab7343c822236832ab407/Screenshot%202024-08-23%20at%2012.52.34%E2%80%AFPM.png" alt="Screenshot 2024-08-23 at 12.52.34 PM.png" />
