### ISSUE TITLE
Steam Reduction Calc Fixes - Suite

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/AMO-Tools-Suite#718]
Issue overview
--------------

See #6686 for Desktop.

Major revisions to math. please see attached.  
There are new fields that need attaching to desktop, I'm not sure it has doxygen documentation at all, but units are in the attached.
There is also a walked through example for most calculation pathways. 
Please let me know if the attached needs any explanation.
[steam reduction calc final.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWVrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81274716a21f9006edb22b00d1163241e7807f16/steam%20reduction%20calc%20final.docx)

**Comment by omerbaa** [comment]
changes made, PR #724
