### ISSUE TITLE
Water Assessment Bindings and Methods

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Suite#719]
Issue overview
--------------
Below is a series of MEASUR inputs => SUITE outputs we need to implement for the water assessment.  If it matters, these are going to be accessed similarly to PHAST losses. i.e. I am entering 4 process uses in measur, iterating through each, processing, sending to suite, and back.

Basic math, but the team would like implemented in suite for consistency. Math is from Kristina but I have changed property names. Let me know if you have questions.

## Process Use
Inputs

```tsx
export interface ProcessUse {
    waterRequired: number,
    waterConsumed: number,
    waterLossInput: number,
    hoursPerYear: number,
    // annual production units
    annualProduction: number
    fractionGrossWaterRecirculated: number,
}
```

Results

```tsx
export interface ProcessUseResults {
    recirculatedWater: number,
    incomingWater: number,
    wasteDischargedAndRecycledOther: number,
}

```

grossWaterUse = waterRequired
- reciruclatedWater = grossWaterUse * fractionGrossWaterRecirculated
- incomingWater = grossWaterUse – reciruclatedWater = grossWaterUse * (1 – fractionGrossWaterRecirculated)
- wasteDischargedAndRecycledOther= incomingWater – waterConsumed – waterLoss
---
## Cooling Tower

Inputs

```tsx
export interface CoolingTower {
    hoursPerYear: number,
    tonnage: number
    loadFactor: number,
    evaporationRateDegree: number,
    temperatureDrop: number,
    makeupConductivity: number,
    blowdownConductivity: number,
}
```

Results

```tsx

export interface CoolingTowerResults {
    grossWaterUse: number,
    evaporationLoss: number,
    cycleOfConcentration: number,
    makeupWater: number,
    blowdownLoss: number,
}

```

- grossWaterUse= 3 * tonnage* loadFactor* 60 * hoursPerYear
- evaporationLoss= (evaporationRateDegree/10) * temperatureDrop* grossWaterUse
- cycleOfConcentration= blowdownConductivity/ makeupConductivity
- makeupWater= evaporationLoss / (1 – (1/cycleOfConcentration))
- blowdownLoss = makeupWater – evaporationLoss

---

## Boiler Water

Inputs

```tsx
export interface BoilerWater {
    hoursPerYear: number,
    power: number
    loadFactor: number,
    steamPerPower: number,
    feedwaterConductivity: number,
    makeupConductivity: number,
    blowdownConductivity: number,
}
```

Results

```tsx

export interface BoilerWaterResults {
    cycleOfConcentration: number,
    grossWaterUse: number,
    makeupWater: number,
    steamLoss: number,
    blowdownLoss: number,
    condensateReturn: number,
    rateOfRecirculation: number
}


```

- cycleOfConcentration = blowdownConductivity/ feedwaterConductivity
- grossWaterUse = operatingHours * power * loadFactor * 0.002 * 60 * steamPerPower / (1 – (1/cycleOfConcentration)) {not sure what 0.002 is, probably density in lb/gal}
- makeupWater = (feedwaterConductivity/makeupWaterConductivity) * grossWaterUse
- blowdownLoss = (1/cycleOfConcentration) * grossWaterUse
- steamLoss = makeupWater – blowdownLoss
- condensateReturn = (1 – (feedwaterConductivity/makeupWaterConductivity)) * grossWaterUse
- rateOfRecirculation = makeupWater/grossWater

---

## Kitchen and Restroom

Inputs

```tsx
export interface KitchenRestroom {
    employeeCount: number,
    workdaysPerYear: number,
    dailyUsePerEmployee: number
}
```

Results

```tsx
grossWaterUse = employeeCount* workdaysPerYear* dailyUsePerEmployee

```
---

## Landscaping

Inputs

```tsx
export interface Landscaping {
    areaIrrigated: number,
    yearlyInchesIrrigated: number,
}
```

- areaIrrigated (in ft2 or m2)
- yearlyInchesIrrigated (in in or cm, convert to ft or m)

Results

```tsx
grossWaterUse = areaIrrigated * yearlyInchesIrrigated (in ft3 or m3, convert to gal for imp)

```
---
## Heat Energy in Discharge (Embodied Energy tab)

Inputs:

```
export interface HeatEnergyInputs {
    incomingTemp: number,
    outgoingTemp: number,
    heaterEfficiency: number,
    heatingFuelType: number,
    wasteWaterDischarge: number
}
```

Results

heatEnergy = wasteWaterDischarge * (outgoingTemp – incomingTemp) * 1 * 8.3454 * heatingEfficiency/1000000

---

## Added Motor Energy

```tsx
export interface MotorEnergy {
    numberUnits: number,
    hoursPerYear: number,
    ratedPower: number,
    loadFactor: number,
    systemEfficiency: number,
}
```

Results

energyUse = ratedPower * numberUnits * motorLoadFactor * operatingHours/systemEfficiency

**Comment by omerbaa** [comment]
Process Use

Do I need this inputs, seems they are duplicates
1. 	waterRequired - grossWaterUseResult
2. 	waterConsumed - waterConsumedResult
3. 	waterLossInput - waterLossResult
4. 	hoursPerYear - annualProduction

In the output do I just resend back the inputs
	grossWaterUseResult, waterConsumedResult, waterLossResult

**Comment by omerbaa** [comment]
Boiler Water
Results 

1. 	What is evaporationLoss, was it suppose to be steamLoss
2. 	Does condensateReturn and rateOfRecirculation need to be added to output / results
3. 	In grossWaterUse = operatingHours * power .... what is operatingHours, is it same as hoursPerYear
4. 	Assuming makeupWaterConductivity in calculation is same as the input makeupConductivity
5. 	Assuming grossWater in calculation is same as calculated grossWaterUse

**Comment by omerbaa** [comment]
Heat Energy in Discharge

1. 	Is heatingFuelType needed
2. 	Assuming input heaterEfficiency and in calculation heatingEfficiency are same.

**Comment by omerbaa** [comment]
Added Motor Energy,  motorLoadFactor in calculation, is it input or calculated

**Comment by nbintertech** [comment]
FYI I updated above description to match below changes:

1. I fixed and made changes above. Sorry - this was a mistake made when I changed some names for MEASUR-side processing
    
2. Boiler
    - Yes, evaporationLoss is now renamed steam loss
    - Updated Boiler object with all missing results
    - All other assumptions correct
3. Yes, assumptions correct. heatingFuelType can just be ignored by the bindings
4. Updated Motor loadFactor added to object
