### ISSUE TITLE
Output WASM files for MEASUR access

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Suite#723]
Issue overview
--------------
Based on Nick, Mark, Omer convo from 7/15 

We need to configure the suite such that WASM file output is automated so we can:
1. Keep ability for MEASUR to npm install a local suite 
2. Keep ability for MEASUR to npm install from a published suite

in either case, MEASUR will look for WASM files, amo_tools_suite.js/wasm and client.js/wasm inside the node_modules folder and copy them into build as needed

**Comment by rmroot** [comment]
The wasm files are published to npm on merges making this issue unnecessary. Closing
